add async and typings with typescript
PrismarineJS/node-yggdrasil pull request #54
Opened 2021-01-03 19:34 UTC by Rob9315

This PR converts yggdrasil to typescript with all functions now being asynchronous, while still retaining the callback compatibility

2021-01-03 20:05 UTC, rom1504 commented on lib/Client.js
> +  auth: async function (options, cb) {
Avoid new Promise and instead convert the inner methods to promise

2021-01-03 20:06 UTC, rom1504 commented
Why the mix between typescript and javascript? Can't we use only javascript ?

2021-01-03 20:08 UTC, Rob9315 commented
will change things up, typescript because of automatic typings

2021-01-08 17:09 UTC, rom1504 requested changes
Can you use ts-standard ? Standard doesn't work with typescript

2021-01-10 17:47 UTC, rom1504 commented
What about the tests ? Not using typescript and async there ?

2021-01-10 17:49 UTC, rom1504 commented on package.json
> +    "pretest": "npm run fix && npm run build",
npm run fix shouldn't run on pretest and prepublish, only non run lint

2021-01-21 08:03 UTC, Kashalls commented
Any updates?

2021-01-21 08:13 UTC, rom1504 commented on package.json
> +    "prepublish": "npm run fix && npm run build",
lint should be there, not fix

2021-01-21 08:14 UTC, rom1504 commented
I left a minor comment, otherwise looks good.
We'll probably remove the callback tests soon but for now let's keep them indeed.

2021-01-21 18:26 UTC, rom1504 approved these changes

2021-01-21 18:26 UTC, merged